version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: smartpick_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smartpick
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - smartpick_network

  redis:
    image: redis:7-alpine
    container_name: smartpick_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - smartpick_network

volumes:
  mongodb_data:

networks:
  smartpick_network:
    driver: bridge
